### ISSUE TITLE
cant generate report for france

### ISSUE THREAD

**Issue by PhilippeBach** [OCA/intrastat-extrastat#27]
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca/intrastat/intrastat_product/models/intrastat_product_declaration.py", line 653, in action_gather
    lines = self._gather_invoices()
  File "/opt/odoo/oca/intrastat/intrastat_product/models/intrastat_product_declaration.py", line 544, in _gather_invoices
    hs_code = inv_line.product_id.product_tmpl_id.\
AttributeError: 'product.template' object has no attribute 'get_hs_code_recursively'

**Comment by rvalyi** [comment]
Hello, this was fixed by this commit I think https://github.com/OCA/intrastat/pull/34
please re-open the issue if you think it is not fixed.

**Comment by rvalyi** [comment]
actually if you are using v8, that could rather be this pending fix, so waiting for you to confirm:
https://github.com/OCA/intrastat/pull/45

**Comment by luc-demeyer** [comment]
Fixed now by merging https://github.com/OCA/intrastat/pull/45.
